title: Oluwadamilola Adeyinka Data Analytics Portfolio
logo: Dami.jpg
description: A data analyst with 2 years experience working across different sectors, highly skilled in SQL, Excel and PowerBi.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
